apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: argocd
spec:
  encryptedData:
    api-key: AgCFvGoykeZx6GmUvXV91gll700HnRAff+z+kpSh4+m/0ed+NY5JlWMw4YWMFZc1WVpjVR1m5D420sNosXIA0FnQIv80h8J3jaEfz1a+iDyhYwIFuXPYPpFO7RTBENsppsZRpTLc0ptqrtPvpFcmeM/t3sqMmkBR2/6a27PcYGBLGfS3h7QlNDAU86g53oU5O8tz1oTgto/tkjZxIiEJBN8tOxxA4iJd/athfmt0PTy4lxUShsh/a2LAbInEOJUcaVAtHSqxZp5ADhN8TGBennVXUsd5zei+mcgUp6XaKJpCA2HVYurOslPLlqQ3fgqlNCOhdckEOJ0kmdco1nW0MWEmzUmGAkBAu6NqQF0rMYMLVXZljTMhzLvwoe0t+OOXKctjoqNOkRPEr2iuvH6MLjJQJODxg6SDy8e+Ds/xuxqiiSBbg3O4D/o81AGBHqlebh+62ZzDz8VhxKM0i4iAcDwrjxJ/DbcKe1Zi0VZjtE0r0lJZ0zcygICxsBruue+tl4N5vrGAqAGwfvAaouUzY6O3Mercys8hUV1y1BPmPyd8o25lBJhLwvREDOKGUSBHTDltLzemxVZhpUEEfMVjBm5TTi3GP4uM8YOc2cVDLptUpmxsfDtxdrx7bJ0eMuguNj0/J9v5d7rosu9WYmFwzlunaqiOaOzXsuKW5CVhS7vSdPGD97rwqPwsrhsyo6h+Vz04fUYh7KtgwYfCSfeAj1nfkOO/Tvdpq89yS7IaZwZFwiJ3uPJG
  template:
    metadata:
      name: cloudflare-api-key
      namespace: argocd
    type: Opaque
