apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeden-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: HEAD
    path: gitops/argocd/applications/kubeden-api
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeden-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true