apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.2  # Replace with the desired ExternalDNS chart version
    chart: external-dns
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare
        cloudflare:
          apiToken:
            secretName: cloudflare-api-token
            secretKey: api-token
          proxied: true  # Set to true if you want Cloudflare to proxy your traffic
        txtOwnerId: "kubeden-k8s"  # A unique identifier for this ExternalDNS instance
        policy: sync  # Use 'upsert-only' if you want to avoid ExternalDNS deleting records
        sources:
          - ingress
        domainFilters:
          - kubeden.io  # Replace with your domain
        annotationFilter: kubernetes.io/ingress.class=nginx
        rbac:
          create: true
          clusterRole: true
        serviceAccount:
          create: true
          name: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns  # Or your preferred namespace
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
