apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
spec:
  encryptedData:
    api-token: AgASsa+rhzIibwEQOVO6EeN7RSFx5RC3HdKO9eP/jAKSS3g1C+qj3jB9tmyYY5OjHZlIJ3bg6FFYM+k+X48E9m+BwqjIA82Vbmwu5rylGL2Sq/J0hGLlXyht5bd9oPjZov9iHJRVuxrF5uOA77Y8K27ZwDc248vxcq5yC4HV+c9D/aBEyBHpDd7kWTnovO/snpY6zHNiO+ksFKc+JyAj3Zlux0iHsT/ypTE1tKtItFMZfVJ+AmQmeFUfyfqIKkZ2zK88A9J1uoijuBrqPv+uB/pdILhXu+cmpGH/5ooTifeHvq7f4FqS3WEwM5/+sh77Acicet11Thu5lhePDSeM6ZZL0vIlSNRBEiBvoNKAN/NVpW1bWuMwJOzMrJH5TP9pWXGgrS+wmvrhb2eV1Km6/Slsor/zswA2qg+9gJNgKGE+HBD+H2bzwue/jZaysxzyyCn6QGv5ziNtOxjuNGHPVpW3VLRp5Y6kirGEusxv5pOv/5YqtHH0Qpwy33fgQaIKPf6VQwqqN6XogjRMu+kBYolw+g8lJv4AUJwTCb4deFe93Ajl3zYbnpsMccINfGkYH0pdCuIyG9/vWznqoHNzeXQw4HImCM3m3bjRcE1iphkPKm85MiSEXTChJJd/Fim6Jm1NDX4CyhPayCzFqRUwEG5FLFTbx9bSgVpN8zg22f5WhYyJosU237Kwc7AXSwGHSCoqhDirQ8bKVHoq4TtkN0n8cgChcTDjDQF9OhLDJwId/XHFZh09QOl1
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque