apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    api-key: AgBG5Hrysj9pHhWtTOHKIY9OaJi+9DJHEhXP6bJxYUdU3HAA9iHsODwCJ9qBCXTA54ZKiKWq0/PjEyFMuYZiPQxxpex5Hxtc08JXeHlhnygWgD4Boon3O4HVTqRYT3F1c460YabOQvUXWlxm9VsFBJ3smZzNbRZQyDa7JNI9l5nmgAp6Kszqcb0/5og0/B04WGj9xAQKMKcwijGmXIQQshG0rkuGKWxQn5Kl4nYArOuMGWZ5i9TWzRyVAa9N5yIUH4206Dl5OmN85FWuJ1wugZnKm+LbKHTlZbQnoKHIaDqJPuwXxz8DKkMXw8gkhhPJShvi9lwtlN+n5U12yc/NplGnw/VneMRI4sJ9IB1ziT7BOQt7sRtYgUePyOAsEby/7zopq+YgmHgzo9ZI1vvZA9GG4qbQ/hvYmwDP72IFuS20MAiHIX+w9TID+N9acx5IZ+Yx9gKt2rAYbs+0oxwooAySZ/z/eMe8VXI5WiV/qU19MupjYBqjnhJFxZzmvP2fqSenBFEBnFMhg6nNOAb2aKeHHZ/Keekz4Q1XxLORYbS0sL2WiRpNbtOeRTQvU6cgfJYyTRlAFhYJQjjjl7634V6DzRpeSeqQ2yNvZHHmLB3qsRTC+G5KobrlrCUe9JQIou6Mz6OH+wSzsNK+awGpOLPt1DHO3ao2Wfffr4bEbkbA6ZjDUqnjMFBHybpdvmSVb+JgL76d/0o6e/sFH7tOHSZ6p7kgvkCREj2BpWTND/yqA1qkF8CR
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
    type: Opaque
