provider: cloudflare
cloudflare:
  secretName: cloudflare-api-token
  proxied: true  # Set to true if you want Cloudflare to proxy your traffic
  email: denislavgavrilov99@gmail.com
txtOwnerId: "kubeden-k8s"  # A unique identifier for this ExternalDNS instance
policy: sync  # Use 'upsert-only' if you want to avoid ExternalDNS deleting records
sources:
  - ingress
domainFilters:
  - kubeden.io  # Replace with your domain
annotationFilter: kubernetes.io/ingress.class=nginx
rbac:
  create: true
  clusterRole: true
serviceAccount:
  create: true
  name: external-dns