{{- if .Values.clusterIssuers }}
{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}