apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.3.2  # Replace with the desired Grafana chart version
    chart: grafana
    helm:
      releaseName: grafana
      values: |
        adminPassword: grafanaadmin  # Replace with a secure password
        
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/tls-acme: "true"
            external-dns.alpha.kubernetes.io/hostname: grafana.kubeden.io
          hosts:
            - grafana.kubeden.io
          path: /
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.kubeden.io
        
        persistence:
          enabled: true
          size: 10Gi
        
        # Additional Grafana settings can be added here
        
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
