apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: markdown-dot-kubeden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: HEAD
    path: kubernetes/argocd/applications/markdown-dot-kubeden
  destination:
    server: https://kubernetes.default.svc
    namespace: markdown-dot-kubeden
  syncPolicy:
    syncOptions:
    - CreateNamespace=true