name: Build and Push Markdown to DigitalOcean

on:
  push:
    branches: [ main ]
    paths:
      - 'nextjs/markdown-dot-kubeden/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'nextjs/markdown-dot-kubeden/**'

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: kubeden/markdown-dot-kubeden

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build container image
      run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) -f nextjs/markdown-dot-kubeden/Dockerfile nextjs/markdown-dot-kubeden

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: |
        docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
        echo $GITHUB_SHA | head -c7 > image_tag.txt

    - name: Upload image tag
      uses: actions/upload-artifact@v4
      with:
        name: image_tag
        path: image_tag.txt